In [76]:
import numpy as np
import pandas as pd

In [77]:
xls = pd.ExcelFile('gesamtdatei_stundenwerte1.xlsx')
df1 = pd.read_excel(xls, 'Jahresdatei 2021')
df1

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015,06-CW-JU-O 27.07.2021,06-CW-JU-W 27.07.2021,02-MI-AL-W 16.12.2021
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,NaN,NaN,8.0,5.0,5.0,...,0.0,2.0,29.0,6.0,4.0,15.0,6.0,NaN,NaN,NaN
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,NaN,NaN,24.0,7.0,23.0,...,2.0,0.0,51.0,7.0,13.0,21.0,4.0,NaN,NaN,NaN
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,NaN,NaN,26.0,23.0,24.0,...,1.0,1.0,51.0,6.0,5.0,25.0,11.0,NaN,NaN,NaN
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,NaN,NaN,24.0,18.0,20.0,...,1.0,3.0,41.0,5.0,3.0,18.0,9.0,NaN,NaN,NaN
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,NaN,NaN,12.0,14.0,19.0,...,1.0,3.0,30.0,6.0,4.0,15.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2021-12-31 19:00:00,32.0,27.0,21.0,29.0,NaN,NaN,3.0,29.0,19.0,...,0.0,4.0,74.0,4.0,10.0,17.0,14.0,13.0,18.0,22.0
8756,2021-12-31 20:00:00,17.0,21.0,14.0,14.0,NaN,NaN,2.0,10.0,13.0,...,0.0,3.0,56.0,15.0,1.0,13.0,13.0,7.0,8.0,8.0
8757,2021-12-31 21:00:00,13.0,23.0,15.0,15.0,NaN,NaN,2.0,8.0,14.0,...,0.0,1.0,26.0,7.0,4.0,4.0,6.0,2.0,8.0,20.0
8758,2021-12-31 22:00:00,25.0,15.0,8.0,11.0,NaN,NaN,2.0,13.0,7.0,...,0.0,1.0,19.0,6.0,2.0,5.0,9.0,5.0,9.0,9.0
8759,2021-12-31 23:00:00,10.0,17.0,10.0,11.0,NaN,NaN,3.0,13.0,6.0,...,0.0,1.0,22.0,3.0,0.0,12.0,4.0,13.0,5.0,9.0

In [78]:
xls2 = pd.ExcelFile('gesamtdatei_stundenwerte1.xlsx')
df2 = pd.read_excel(xls2, 'Jahresdatei 2020')
df2

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,18-TS-YOR-O 01.04.2015,18-TS-YOR-W 01.04.2015,19-TS-MON 01.05.2015,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015
0,2020-01-01 00:00:00,12.0,15.0,8.0,8.0,0.0,0.0,4.0,4.0,5.0,...,1.0,14.0,10.0,1.0,0.0,7.0,2.0,0.0,12.0,5.0
1,2020-01-01 01:00:00,15.0,18.0,14.0,18.0,0.0,0.0,11.0,4.0,20.0,...,6.0,17.0,15.0,1.0,4.0,26.0,5.0,11.0,21.0,7.0
2,2020-01-01 02:00:00,16.0,29.0,12.0,13.0,0.0,0.0,14.0,4.0,23.0,...,5.0,23.0,26.0,3.0,6.0,47.0,7.0,11.0,28.0,9.0
3,2020-01-01 03:00:00,25.0,22.0,6.0,15.0,0.0,0.0,11.0,10.0,15.0,...,6.0,15.0,39.0,2.0,5.0,46.0,7.0,7.0,23.0,3.0
4,2020-01-01 04:00:00,21.0,11.0,8.0,10.0,0.0,0.0,9.0,6.0,8.0,...,9.0,14.0,13.0,3.0,3.0,31.0,7.0,1.0,13.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,2020-12-31 19:00:00,73.0,73.0,44.0,36.0,NaN,NaN,29.0,34.0,58.0,...,50.0,52.0,84.0,4.0,2.0,137.0,26.0,13.0,24.0,21.0
8780,2020-12-31 20:00:00,38.0,49.0,31.0,30.0,NaN,NaN,46.0,20.0,35.0,...,33.0,36.0,56.0,6.0,1.0,74.0,15.0,3.0,23.0,12.0
8781,2020-12-31 21:00:00,29.0,20.0,15.0,18.0,NaN,NaN,23.0,18.0,14.0,...,16.0,19.0,19.0,3.0,4.0,39.0,11.0,1.0,15.0,5.0
8782,2020-12-31 22:00:00,16.0,18.0,11.0,14.0,NaN,NaN,11.0,16.0,19.0,...,20.0,11.0,22.0,0.0,1.0,38.0,7.0,1.0,18.0,6.0
8783,2020-12-31 23:00:00,15.0,14.0,10.0,7.0,NaN,NaN,9.0,9.0,16.0,...,8.0,8.0,20.0,0.0,3.0,25.0,5.0,1.0,26.0,6.0

In [79]:
df=df1.append(df2)
df

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015,06-CW-JU-O 27.07.2021,06-CW-JU-W 27.07.2021,02-MI-AL-W 16.12.2021
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,NaN,NaN,8.0,5.0,5.0,...,0.0,2.0,29.0,6.0,4.0,15.0,6.0,NaN,NaN,NaN
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,NaN,NaN,24.0,7.0,23.0,...,2.0,0.0,51.0,7.0,13.0,21.0,4.0,NaN,NaN,NaN
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,NaN,NaN,26.0,23.0,24.0,...,1.0,1.0,51.0,6.0,5.0,25.0,11.0,NaN,NaN,NaN
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,NaN,NaN,24.0,18.0,20.0,...,1.0,3.0,41.0,5.0,3.0,18.0,9.0,NaN,NaN,NaN
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,NaN,NaN,12.0,14.0,19.0,...,1.0,3.0,30.0,6.0,4.0,15.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,2020-12-31 19:00:00,73.0,73.0,44.0,36.0,NaN,NaN,29.0,34.0,58.0,...,4.0,2.0,137.0,26.0,13.0,24.0,21.0,NaN,NaN,NaN
8780,2020-12-31 20:00:00,38.0,49.0,31.0,30.0,NaN,NaN,46.0,20.0,35.0,...,6.0,1.0,74.0,15.0,3.0,23.0,12.0,NaN,NaN,NaN
8781,2020-12-31 21:00:00,29.0,20.0,15.0,18.0,NaN,NaN,23.0,18.0,14.0,...,3.0,4.0,39.0,11.0,1.0,15.0,5.0,NaN,NaN,NaN
8782,2020-12-31 22:00:00,16.0,18.0,11.0,14.0,NaN,NaN,11.0,16.0,19.0,...,0.0,1.0,38.0,7.0,1.0,18.0,6.0,NaN,NaN,NaN
8783,2020-12-31 23:00:00,15.0,14.0,10.0,7.0,NaN,NaN,9.0,9.0,16.0,...,0.0,3.0,25.0,5.0,1.0,26.0,6.0,NaN,NaN,NaN

In [80]:
xls3 = pd.ExcelFile('gesamtdatei_stundenwerte1.xlsx')
df3 = pd.read_excel(xls3, 'Jahresdatei 2019')
df3

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,18-TS-YOR-O 01.04.2015,18-TS-YOR-W 01.04.2015,19-TS-MON 01.05.2015,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015
0,2019-01-01 00:00:00,11.0,13.0,0.0,8.0,12.0,8.0,7.0,17.0,5.0,...,4,0.0,15,0.0,0.0,7.0,0.0,0,13.0,3.0
1,2019-01-01 01:00:00,16.0,9.0,0.0,7.0,33.0,31.0,7.0,1.0,19.0,...,13,0.0,26,1.0,1.0,52.0,1.0,7,16.0,5.0
2,2019-01-01 02:00:00,19.0,18.0,0.0,13.0,26.0,38.0,9.0,3.0,22.0,...,26,0.0,34,2.0,2.0,48.0,5.0,1,18.0,11.0
3,2019-01-01 03:00:00,19.0,19.0,0.0,9.0,40.0,28.0,11.0,6.0,21.0,...,14,0.0,30,1.0,1.0,38.0,3.0,4,16.0,7.0
4,2019-01-01 04:00:00,13.0,15.0,0.0,5.0,32.0,31.0,18.0,3.0,5.0,...,15,0.0,14,1.0,4.0,30.0,6.0,0,10.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8754,2019-12-31 19:00:00,45.0,38.0,24.0,17.0,0.0,0.0,18.0,14.0,45.0,...,13,34.0,45,4.0,4.0,71.0,12.0,8,39.0,13.0
8755,2019-12-31 20:00:00,30.0,37.0,17.0,15.0,0.0,0.0,25.0,17.0,22.0,...,7,28.0,28,4.0,2.0,70.0,12.0,0,11.0,6.0
8756,2019-12-31 21:00:00,22.0,28.0,17.0,11.0,0.0,0.0,10.0,6.0,22.0,...,6,18.0,18,2.0,1.0,34.0,5.0,0,22.0,11.0
8757,2019-12-31 22:00:00,22.0,20.0,11.0,13.0,0.0,0.0,7.0,9.0,22.0,...,3,10.0,19,2.0,1.0,26.0,5.0,0,11.0,2.0
8758,2019-12-31 23:00:00,13.0,15.0,15.0,13.0,0.0,0.0,7.0,5.0,13.0,...,2,11.0,21,2.0,1.0,34.0,6.0,0,13.0,7.0

In [81]:
df_all=df.append(df3)
df_all

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015,06-CW-JU-O 27.07.2021,06-CW-JU-W 27.07.2021,02-MI-AL-W 16.12.2021
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,NaN,NaN,8.0,5.0,5.0,...,0.0,2.0,29.0,6.0,4.0,15.0,6.0,NaN,NaN,NaN
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,NaN,NaN,24.0,7.0,23.0,...,2.0,0.0,51.0,7.0,13.0,21.0,4.0,NaN,NaN,NaN
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,NaN,NaN,26.0,23.0,24.0,...,1.0,1.0,51.0,6.0,5.0,25.0,11.0,NaN,NaN,NaN
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,NaN,NaN,24.0,18.0,20.0,...,1.0,3.0,41.0,5.0,3.0,18.0,9.0,NaN,NaN,NaN
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,NaN,NaN,12.0,14.0,19.0,...,1.0,3.0,30.0,6.0,4.0,15.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8754,2019-12-31 19:00:00,45.0,38.0,24.0,17.0,0.0,0.0,18.0,14.0,45.0,...,4.0,4.0,71.0,12.0,8.0,39.0,13.0,NaN,NaN,NaN
8755,2019-12-31 20:00:00,30.0,37.0,17.0,15.0,0.0,0.0,25.0,17.0,22.0,...,4.0,2.0,70.0,12.0,0.0,11.0,6.0,NaN,NaN,NaN
8756,2019-12-31 21:00:00,22.0,28.0,17.0,11.0,0.0,0.0,10.0,6.0,22.0,...,2.0,1.0,34.0,5.0,0.0,22.0,11.0,NaN,NaN,NaN
8757,2019-12-31 22:00:00,22.0,20.0,11.0,13.0,0.0,0.0,7.0,9.0,22.0,...,2.0,1.0,26.0,5.0,0.0,11.0,2.0,NaN,NaN,NaN
8758,2019-12-31 23:00:00,13.0,15.0,15.0,13.0,0.0,0.0,7.0,5.0,13.0,...,2.0,1.0,34.0,6.0,0.0,13.0,7.0,NaN,NaN,NaN

In [82]:
xls4 = pd.ExcelFile('gesamtdatei_stundenwerte1.xlsx')
df4 = pd.read_excel(xls4, 'Jahresdatei 2018')
df4

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,18-TS-YOR-O 01.04.2015,18-TS-YOR-W 01.04.2015,19-TS-MON 01.05.2015,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015
0,2018-01-01 00:00:00,12,9,15,1,11,18,3.0,6,18,...,7,7,7.0,1,0,9,3,0,11,0
1,2018-01-01 01:00:00,17,16,7,7,26,22,8.0,2,24,...,5,9,21.0,2,1,40,6,0,12,5
2,2018-01-01 02:00:00,25,18,5,12,39,20,11.0,12,23,...,21,16,34.0,1,0,46,1,1,20,7
3,2018-01-01 03:00:00,18,19,8,13,51,22,7.0,6,21,...,18,17,33.0,2,1,43,4,2,11,2
4,2018-01-01 04:00:00,15,12,6,3,27,29,6.0,4,11,...,8,9,17.0,4,0,29,7,0,6,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2018-12-31 19:00:00,36,41,0,22,94,61,11.0,17,29,...,34,0,40.0,7,6,85,9,2,37,7
8756,2018-12-31 20:00:00,32,24,0,8,85,58,9.0,13,23,...,18,0,31.0,2,5,50,9,3,14,9
8757,2018-12-31 21:00:00,25,33,0,16,54,32,13.0,14,11,...,11,0,36.0,3,2,39,5,6,14,4
8758,2018-12-31 22:00:00,21,22,0,11,44,42,9.0,4,7,...,18,0,17.0,1,2,30,3,2,10,4
8759,2018-12-31 23:00:00,26,18,0,12,36,28,16.0,4,3,...,16,0,30.0,0,1,23,2,0,19,3

In [83]:
df_years=df_all.append(df4)
df_years

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015,06-CW-JU-O 27.07.2021,06-CW-JU-W 27.07.2021,02-MI-AL-W 16.12.2021
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,NaN,NaN,8.0,5.0,5.0,...,0.0,2.0,29.0,6.0,4.0,15.0,6.0,NaN,NaN,NaN
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,NaN,NaN,24.0,7.0,23.0,...,2.0,0.0,51.0,7.0,13.0,21.0,4.0,NaN,NaN,NaN
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,NaN,NaN,26.0,23.0,24.0,...,1.0,1.0,51.0,6.0,5.0,25.0,11.0,NaN,NaN,NaN
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,NaN,NaN,24.0,18.0,20.0,...,1.0,3.0,41.0,5.0,3.0,18.0,9.0,NaN,NaN,NaN
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,NaN,NaN,12.0,14.0,19.0,...,1.0,3.0,30.0,6.0,4.0,15.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2018-12-31 19:00:00,36.0,41.0,0.0,22.0,94.0,61.0,11.0,17.0,29.0,...,7.0,6.0,85.0,9.0,2.0,37.0,7.0,NaN,NaN,NaN
8756,2018-12-31 20:00:00,32.0,24.0,0.0,8.0,85.0,58.0,9.0,13.0,23.0,...,2.0,5.0,50.0,9.0,3.0,14.0,9.0,NaN,NaN,NaN
8757,2018-12-31 21:00:00,25.0,33.0,0.0,16.0,54.0,32.0,13.0,14.0,11.0,...,3.0,2.0,39.0,5.0,6.0,14.0,4.0,NaN,NaN,NaN
8758,2018-12-31 22:00:00,21.0,22.0,0.0,11.0,44.0,42.0,9.0,4.0,7.0,...,1.0,2.0,30.0,3.0,2.0,10.0,4.0,NaN,NaN,NaN
8759,2018-12-31 23:00:00,26.0,18.0,0.0,12.0,36.0,28.0,16.0,4.0,3.0,...,0.0,1.0,23.0,2.0,0.0,19.0,3.0,NaN,NaN,NaN

In [84]:
xls5= pd.ExcelFile('gesamtdatei_stundenwerte1.xlsx')
df5 = pd.read_excel(xls5, 'Jahresdatei 2017')
df5

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,18-TS-YOR-O 01.04.2015,18-TS-YOR-W 01.04.2015,19-TS-MON 01.05.2015,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015
0,2017-01-01 00:00:00,6,5,4,5,16,11,2,6,56,...,8.0,7,6,1,2.0,6,3.0,2,3,2
1,2017-01-01 01:00:00,23,16,5,11,26,28,5,7,31,...,10.0,15,19,4,0.0,31,4.0,6,14,2
2,2017-01-01 02:00:00,17,16,15,11,45,24,9,7,32,...,30.0,14,19,3,5.0,53,2.0,1,15,5
3,2017-01-01 03:00:00,22,22,9,17,52,37,3,7,47,...,17.0,15,22,4,2.0,36,2.0,0,8,1
4,2017-01-01 04:00:00,14,19,4,9,42,18,10,6,14,...,9.0,11,8,2,2.0,34,3.0,0,14,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2017-12-31 19:00:00,29,29,19,14,69,51,20,3,109,...,28.0,23,36,11,8.0,82,3.0,3,27,4
8756,2017-12-31 20:00:00,31,22,16,15,63,52,26,13,102,...,16.0,17,45,4,7.0,52,3.0,0,19,5
8757,2017-12-31 21:00:00,21,18,11,5,41,41,7,7,91,...,13.0,12,20,5,1.0,30,2.0,3,18,2
8758,2017-12-31 22:00:00,11,18,6,10,30,48,10,3,106,...,13.0,8,27,2,0.0,35,5.0,0,16,2
8759,2017-12-31 23:00:00,7,9,10,20,25,28,5,8,77,...,5.0,8,17,2,0.0,36,0.0,0,17,4

In [85]:
df_5years=df_years.append(df5)
df_5years

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015,06-CW-JU-O 27.07.2021,06-CW-JU-W 27.07.2021,02-MI-AL-W 16.12.2021
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,NaN,NaN,8.0,5.0,5.0,...,0.0,2.0,29.0,6.0,4.0,15.0,6.0,NaN,NaN,NaN
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,NaN,NaN,24.0,7.0,23.0,...,2.0,0.0,51.0,7.0,13.0,21.0,4.0,NaN,NaN,NaN
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,NaN,NaN,26.0,23.0,24.0,...,1.0,1.0,51.0,6.0,5.0,25.0,11.0,NaN,NaN,NaN
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,NaN,NaN,24.0,18.0,20.0,...,1.0,3.0,41.0,5.0,3.0,18.0,9.0,NaN,NaN,NaN
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,NaN,NaN,12.0,14.0,19.0,...,1.0,3.0,30.0,6.0,4.0,15.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2017-12-31 19:00:00,29.0,29.0,19.0,14.0,69.0,51.0,20.0,3.0,109.0,...,11.0,8.0,82.0,3.0,3.0,27.0,4.0,NaN,NaN,NaN
8756,2017-12-31 20:00:00,31.0,22.0,16.0,15.0,63.0,52.0,26.0,13.0,102.0,...,4.0,7.0,52.0,3.0,0.0,19.0,5.0,NaN,NaN,NaN
8757,2017-12-31 21:00:00,21.0,18.0,11.0,5.0,41.0,41.0,7.0,7.0,91.0,...,5.0,1.0,30.0,2.0,3.0,18.0,2.0,NaN,NaN,NaN
8758,2017-12-31 22:00:00,11.0,18.0,6.0,10.0,30.0,48.0,10.0,3.0,106.0,...,2.0,0.0,35.0,5.0,0.0,16.0,2.0,NaN,NaN,NaN
8759,2017-12-31 23:00:00,7.0,9.0,10.0,20.0,25.0,28.0,5.0,8.0,77.0,...,2.0,0.0,36.0,0.0,0.0,17.0,4.0,NaN,NaN,NaN

In [87]:
df_5years = df_5years.drop(['05-FK-OBB-O 01.06.2015', '05-FK-OBB-W 01.06.2015', '06-CW-JU-O 27.07.2021', '06-CW-JU-W 27.07.2021', '02-MI-AL-W 16.12.2021'  ], axis=1)
df_5years

,ZÃ¤hlstelle Inbetriebnahme,JannowitzbrÃ¼cke Nord,JannowitzbrÃ¼cke SÃ¼d,InvalidenstraÃe Ost,InvalidenstraÃe West,Frankfurter Allee Ost,Frankfurter Allee West,Berliner StraÃe Nord,Berliner StraÃe SÃ¼d,Schwedter Steg,...,YorckstraÃe Ost,YorkstraÃe West,MonumentenstraÃe,Mariendorfer Damm Nord,Mariendorfer Damm SÃ¼d,Maybachufer,Kaisersteg,AlberichstraÃe,Paul-und-Paula-Uferweg,MarkstraÃe
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,8.0,5.0,5.0,7.0,17.0,...,7.0,9.0,21.0,0.0,2.0,29.0,6.0,4.0,15.0,6.0
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,24.0,7.0,23.0,21.0,14.0,...,27.0,26.0,33.0,2.0,0.0,51.0,7.0,13.0,21.0,4.0
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,26.0,23.0,24.0,32.0,14.0,...,30.0,35.0,48.0,1.0,1.0,51.0,6.0,5.0,25.0,11.0
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,24.0,18.0,20.0,20.0,22.0,...,33.0,16.0,33.0,1.0,3.0,41.0,5.0,3.0,18.0,9.0
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,12.0,14.0,19.0,8.0,2.0,...,13.0,12.0,30.0,1.0,3.0,30.0,6.0,4.0,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2017-12-31 19:00:00,29.0,29.0,19.0,14.0,20.0,3.0,109.0,18.0,28.0,...,28.0,23.0,36.0,11.0,8.0,82.0,3.0,3.0,27.0,4.0
8756,2017-12-31 20:00:00,31.0,22.0,16.0,15.0,26.0,13.0,102.0,27.0,12.0,...,16.0,17.0,45.0,4.0,7.0,52.0,3.0,0.0,19.0,5.0
8757,2017-12-31 21:00:00,21.0,18.0,11.0,5.0,7.0,7.0,91.0,13.0,11.0,...,13.0,12.0,20.0,5.0,1.0,30.0,2.0,3.0,18.0,2.0
8758,2017-12-31 22:00:00,11.0,18.0,6.0,10.0,10.0,3.0,106.0,9.0,15.0,...,13.0,8.0,27.0,2.0,0.0,35.0,5.0,0.0,16.0,2.0
8759,2017-12-31 23:00:00,7.0,9.0,10.0,20.0,5.0,8.0,77.0,6.0,8.0,...,5.0,8.0,17.0,2.0,0.0,36.0,0.0,0.0,17.0,4.0

In [88]:
df_5years= df_5years.rename(columns={'02-MI-JAN-N 01.04.2015': 'JannowitzbrÃ¼cke Nord', '02-MI-JAN-S 01.04.2015': 'JannowitzbrÃ¼cke SÃ¼d',
                         '03-MI-SAN-O 01.06.2015': 'InvalidenstraÃe Ost', '03-MI-SAN-W 01.06.2015': 'InvalidenstraÃe West',
                         '06-FK-FRA-O 01.06.2016': 'Frankfurter Allee Ost', '06-FK-FRA-W 01.06.2016': 'Frankfurter Allee West',
                         '10-PA-BER-N 01.05.2016': 'Berliner StraÃe Nord', '10-PA-BER-S 01.05.2016': 'Berliner StraÃe SÃ¼d',
                         '12-PA-SCH 01.03.2012': 'Schwedter Steg', '13-CW-PRI 01.04.2015': 'PrinzregentenstraÃe',
                         '15-SP-KLO-N 01.06.2016': 'KlosterstraÃe Nord', '15-SP-KLO-S 01.06.2016': 'KlosterstraÃe SÃ¼d',
                         '17-SZ-BRE-O 01.05.2016': 'Breitenbachplatz Ost', '17-SZ-BRE-W 01.05.2016': 'Breitenbachplatz West',
                         '18-TS-YOR-O 01.04.2015': 'YorckstraÃe Ost', '18-TS-YOR-W 01.04.2015': 'YorkstraÃe West',
                         '19-TS-MON 01.05.2015': 'MonumentenstraÃe', '20-TS-MAR-N  01.05.2016': 'Mariendorfer Damm Nord',
                         '20-TS-MAR-S 01.05.2016': 'Mariendorfer Damm SÃ¼d', '21-NK-MAY 01.05.2016': 'Maybachufer',
                         '23-TK-KAI 01.05.2016': 'Kaisersteg', '24-MH-ALB 01.07.2015': 'AlberichstraÃe',
                         '26-LI-PUP 01.06.2015': 'Paul-und-Paula-Uferweg', '27-RE-MAR 01.05.2015': 'MarkstraÃe'})
df_5years

,ZÃ¤hlstelle Inbetriebnahme,JannowitzbrÃ¼cke Nord,JannowitzbrÃ¼cke SÃ¼d,InvalidenstraÃe Ost,InvalidenstraÃe West,Frankfurter Allee Ost,Frankfurter Allee West,Berliner StraÃe Nord,Berliner StraÃe SÃ¼d,Schwedter Steg,...,YorckstraÃe Ost,YorkstraÃe West,MonumentenstraÃe,Mariendorfer Damm Nord,Mariendorfer Damm SÃ¼d,Maybachufer,Kaisersteg,AlberichstraÃe,Paul-und-Paula-Uferweg,MarkstraÃe
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,8.0,5.0,5.0,7.0,17.0,...,7.0,9.0,21.0,0.0,2.0,29.0,6.0,4.0,15.0,6.0
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,24.0,7.0,23.0,21.0,14.0,...,27.0,26.0,33.0,2.0,0.0,51.0,7.0,13.0,21.0,4.0
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,26.0,23.0,24.0,32.0,14.0,...,30.0,35.0,48.0,1.0,1.0,51.0,6.0,5.0,25.0,11.0
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,24.0,18.0,20.0,20.0,22.0,...,33.0,16.0,33.0,1.0,3.0,41.0,5.0,3.0,18.0,9.0
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,12.0,14.0,19.0,8.0,2.0,...,13.0,12.0,30.0,1.0,3.0,30.0,6.0,4.0,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2017-12-31 19:00:00,29.0,29.0,19.0,14.0,20.0,3.0,109.0,18.0,28.0,...,28.0,23.0,36.0,11.0,8.0,82.0,3.0,3.0,27.0,4.0
8756,2017-12-31 20:00:00,31.0,22.0,16.0,15.0,26.0,13.0,102.0,27.0,12.0,...,16.0,17.0,45.0,4.0,7.0,52.0,3.0,0.0,19.0,5.0
8757,2017-12-31 21:00:00,21.0,18.0,11.0,5.0,7.0,7.0,91.0,13.0,11.0,...,13.0,12.0,20.0,5.0,1.0,30.0,2.0,3.0,18.0,2.0
8758,2017-12-31 22:00:00,11.0,18.0,6.0,10.0,10.0,3.0,106.0,9.0,15.0,...,13.0,8.0,27.0,2.0,0.0,35.0,5.0,0.0,16.0,2.0
8759,2017-12-31 23:00:00,7.0,9.0,10.0,20.0,5.0,8.0,77.0,6.0,8.0,...,5.0,8.0,17.0,2.0,0.0,36.0,0.0,0.0,17.0,4.0

In [89]:
df_5years['date'] = df_5years['ZÃ¤hlstelle        Inbetriebnahme'].dt.date
df_5years['Time'] = df_5years['ZÃ¤hlstelle        Inbetriebnahme'].dt.time


df_5years

,ZÃ¤hlstelle Inbetriebnahme,JannowitzbrÃ¼cke Nord,JannowitzbrÃ¼cke SÃ¼d,InvalidenstraÃe Ost,InvalidenstraÃe West,Frankfurter Allee Ost,Frankfurter Allee West,Berliner StraÃe Nord,Berliner StraÃe SÃ¼d,Schwedter Steg,...,MonumentenstraÃe,Mariendorfer Damm Nord,Mariendorfer Damm SÃ¼d,Maybachufer,Kaisersteg,AlberichstraÃe,Paul-und-Paula-Uferweg,MarkstraÃe,date,Time
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,8.0,5.0,5.0,7.0,17.0,...,21.0,0.0,2.0,29.0,6.0,4.0,15.0,6.0,2021-01-01,00:00:00
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,24.0,7.0,23.0,21.0,14.0,...,33.0,2.0,0.0,51.0,7.0,13.0,21.0,4.0,2021-01-01,01:00:00
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,26.0,23.0,24.0,32.0,14.0,...,48.0,1.0,1.0,51.0,6.0,5.0,25.0,11.0,2021-01-01,02:00:00
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,24.0,18.0,20.0,20.0,22.0,...,33.0,1.0,3.0,41.0,5.0,3.0,18.0,9.0,2021-01-01,03:00:00
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,12.0,14.0,19.0,8.0,2.0,...,30.0,1.0,3.0,30.0,6.0,4.0,15.0,1.0,2021-01-01,04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2017-12-31 19:00:00,29.0,29.0,19.0,14.0,20.0,3.0,109.0,18.0,28.0,...,36.0,11.0,8.0,82.0,3.0,3.0,27.0,4.0,2017-12-31,19:00:00
8756,2017-12-31 20:00:00,31.0,22.0,16.0,15.0,26.0,13.0,102.0,27.0,12.0,...,45.0,4.0,7.0,52.0,3.0,0.0,19.0,5.0,2017-12-31,20:00:00
8757,2017-12-31 21:00:00,21.0,18.0,11.0,5.0,7.0,7.0,91.0,13.0,11.0,...,20.0,5.0,1.0,30.0,2.0,3.0,18.0,2.0,2017-12-31,21:00:00
8758,2017-12-31 22:00:00,11.0,18.0,6.0,10.0,10.0,3.0,106.0,9.0,15.0,...,27.0,2.0,0.0,35.0,5.0,0.0,16.0,2.0,2017-12-31,22:00:00
8759,2017-12-31 23:00:00,7.0,9.0,10.0,20.0,5.0,8.0,77.0,6.0,8.0,...,17.0,2.0,0.0,36.0,0.0,0.0,17.0,4.0,2017-12-31,23:00:00

In [56]:
df_5years.to_excel("5_years_together.xlsx")

In [90]:
df_5years.isna()

,ZÃ¤hlstelle Inbetriebnahme,JannowitzbrÃ¼cke Nord,JannowitzbrÃ¼cke SÃ¼d,InvalidenstraÃe Ost,InvalidenstraÃe West,Frankfurter Allee Ost,Frankfurter Allee West,Berliner StraÃe Nord,Berliner StraÃe SÃ¼d,Schwedter Steg,...,MonumentenstraÃe,Mariendorfer Damm Nord,Mariendorfer Damm SÃ¼d,Maybachufer,Kaisersteg,AlberichstraÃe,Paul-und-Paula-Uferweg,MarkstraÃe,date,Time
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8756,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8757,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8758,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8759,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [91]:
df_5years.isna().sum()

ZÃ¤hlstelle        Inbetriebnahme      0
JannowitzbrÃ¼cke Nord                  4
JannowitzbrÃ¼cke SÃ¼d                   4
InvalidenstraÃe Ost                   4
InvalidenstraÃe West                 12
Frankfurter Allee Ost                13
Frankfurter Allee West                4
Berliner StraÃe Nord                  4
Berliner StraÃe SÃ¼d                   5
Schwedter Steg                        3
PrinzregentenstraÃe                   4
KlosterstraÃe Nord                   19
KlosterstraÃe SÃ¼d                     4
Breitenbachplatz Ost                  4
Breitenbachplatz West                 4
YorckstraÃe Ost                      15
YorkstraÃe West                       4
MonumentenstraÃe                     15
Mariendorfer Damm Nord                4
Mariendorfer Damm SÃ¼d               488
Maybachufer                           4
Kaisersteg                          214
AlberichstraÃe                        2
Paul-und-Paula-Uferweg                4
MarkstraÃe                            4
date                                  0
Time                                  0
dtype: int64

In [92]:
xls6= pd.ExcelFile('gesamtdatei_stundenwerte_with_2022.xlsx')
df6 = pd.read_excel(xls6, 'Jahresdatei 2022')
df6

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 02.05.2022,05-FK-OBB-W 02.05.2022,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015,14-CW-JU-O 27.07.2021,14-CW-JU-W 27.07.2021,01-MI-AL-W 16.12.2021,11-PA-SE-N\n06.10.2022
0,2022-01-01 00:00:00,10.0,11.0,9.0,8.0,NaN,NaN,6.0,13.0,7.0,...,4.0,24.0,2.0,2.0,6.0,3.0,7.0,9.0,9.0,NaN
1,2022-01-01 01:00:00,22.0,13.0,12.0,6.0,NaN,NaN,4.0,9.0,14.0,...,1.0,48.0,7.0,4.0,7.0,7.0,5.0,5.0,9.0,NaN
2,2022-01-01 02:00:00,25.0,10.0,14.0,9.0,NaN,NaN,4.0,12.0,19.0,...,4.0,22.0,9.0,0.0,13.0,8.0,4.0,7.0,11.0,NaN
3,2022-01-01 03:00:00,12.0,21.0,13.0,17.0,NaN,NaN,3.0,13.0,9.0,...,0.0,44.0,7.0,3.0,7.0,5.0,3.0,6.0,3.0,NaN
4,2022-01-01 04:00:00,8.0,6.0,6.0,4.0,NaN,NaN,0.0,12.0,10.0,...,3.0,39.0,5.0,0.0,11.0,7.0,1.0,5.0,11.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00:00,36.0,54.0,28.0,36.0,104.0,100.0,28.0,25.0,23.0,...,3.0,89.0,14.0,15.0,38.0,20.0,21.0,16.0,21.0,69.0
8756,2022-12-31 20:00:00,32.0,32.0,20.0,38.0,78.0,66.0,31.0,23.0,22.0,...,6.0,65.0,14.0,3.0,20.0,10.0,10.0,19.0,25.0,63.0
8757,2022-12-31 21:00:00,24.0,35.0,16.0,11.0,49.0,38.0,9.0,18.0,13.0,...,4.0,40.0,10.0,2.0,19.0,10.0,11.0,15.0,19.0,29.0
8758,2022-12-31 22:00:00,32.0,29.0,13.0,19.0,64.0,47.0,17.0,14.0,11.0,...,2.0,37.0,9.0,7.0,8.0,4.0,12.0,6.0,35.0,41.0
8759,2022-12-31 23:00:00,22.0,17.0,10.0,12.0,34.0,29.0,10.0,15.0,8.0,...,2.0,29.0,14.0,4.0,18.0,3.0,21.0,9.0,7.0,19.0

In [93]:
df6= df6.drop(['05-FK-OBB-O 02.05.2022', '05-FK-OBB-W 02.05.2022', '14-CW-JU-O 27.07.2021', '14-CW-JU-W 27.07.2021', '01-MI-AL-W 16.12.2021' ], axis=1)
df6

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,10-PA-BER-S 01.05.2016,12-PA-SCH 01.03.2012,...,18-TS-YOR-W 01.04.2015,19-TS-MON 01.05.2015,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015,11-PA-SE-N\n06.10.2022
0,2022-01-01 00:00:00,10.0,11.0,9.0,8.0,6.0,13.0,7.0,6.0,12.0,...,11.0,12.0,0.0,4.0,24.0,2.0,2.0,6.0,3.0,NaN
1,2022-01-01 01:00:00,22.0,13.0,12.0,6.0,4.0,9.0,14.0,12.0,12.0,...,19.0,20.0,0.0,1.0,48.0,7.0,4.0,7.0,7.0,NaN
2,2022-01-01 02:00:00,25.0,10.0,14.0,9.0,4.0,12.0,19.0,13.0,12.0,...,18.0,32.0,0.0,4.0,22.0,9.0,0.0,13.0,8.0,NaN
3,2022-01-01 03:00:00,12.0,21.0,13.0,17.0,3.0,13.0,9.0,10.0,9.0,...,15.0,25.0,0.0,0.0,44.0,7.0,3.0,7.0,5.0,NaN
4,2022-01-01 04:00:00,8.0,6.0,6.0,4.0,0.0,12.0,10.0,13.0,3.0,...,14.0,14.0,0.0,3.0,39.0,5.0,0.0,11.0,7.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00:00,36.0,54.0,28.0,36.0,28.0,25.0,23.0,39.0,30.0,...,50.0,44.0,6.0,3.0,89.0,14.0,15.0,38.0,20.0,69.0
8756,2022-12-31 20:00:00,32.0,32.0,20.0,38.0,31.0,23.0,22.0,38.0,29.0,...,21.0,44.0,3.0,6.0,65.0,14.0,3.0,20.0,10.0,63.0
8757,2022-12-31 21:00:00,24.0,35.0,16.0,11.0,9.0,18.0,13.0,25.0,7.0,...,24.0,17.0,13.0,4.0,40.0,10.0,2.0,19.0,10.0,29.0
8758,2022-12-31 22:00:00,32.0,29.0,13.0,19.0,17.0,14.0,11.0,15.0,14.0,...,18.0,16.0,6.0,2.0,37.0,9.0,7.0,8.0,4.0,41.0
8759,2022-12-31 23:00:00,22.0,17.0,10.0,12.0,10.0,15.0,8.0,14.0,14.0,...,18.0,18.0,6.0,2.0,29.0,14.0,4.0,18.0,3.0,19.0

In [94]:
df6= df6.drop(['11-PA-SE-N\n06.10.2022' ], axis=1)
df6

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,10-PA-BER-S 01.05.2016,12-PA-SCH 01.03.2012,...,18-TS-YOR-O 01.04.2015,18-TS-YOR-W 01.04.2015,19-TS-MON 01.05.2015,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015
0,2022-01-01 00:00:00,10.0,11.0,9.0,8.0,6.0,13.0,7.0,6.0,12.0,...,8.0,11.0,12.0,0.0,4.0,24.0,2.0,2.0,6.0,3.0
1,2022-01-01 01:00:00,22.0,13.0,12.0,6.0,4.0,9.0,14.0,12.0,12.0,...,17.0,19.0,20.0,0.0,1.0,48.0,7.0,4.0,7.0,7.0
2,2022-01-01 02:00:00,25.0,10.0,14.0,9.0,4.0,12.0,19.0,13.0,12.0,...,18.0,18.0,32.0,0.0,4.0,22.0,9.0,0.0,13.0,8.0
3,2022-01-01 03:00:00,12.0,21.0,13.0,17.0,3.0,13.0,9.0,10.0,9.0,...,19.0,15.0,25.0,0.0,0.0,44.0,7.0,3.0,7.0,5.0
4,2022-01-01 04:00:00,8.0,6.0,6.0,4.0,0.0,12.0,10.0,13.0,3.0,...,12.0,14.0,14.0,0.0,3.0,39.0,5.0,0.0,11.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00:00,36.0,54.0,28.0,36.0,28.0,25.0,23.0,39.0,30.0,...,38.0,50.0,44.0,6.0,3.0,89.0,14.0,15.0,38.0,20.0
8756,2022-12-31 20:00:00,32.0,32.0,20.0,38.0,31.0,23.0,22.0,38.0,29.0,...,16.0,21.0,44.0,3.0,6.0,65.0,14.0,3.0,20.0,10.0
8757,2022-12-31 21:00:00,24.0,35.0,16.0,11.0,9.0,18.0,13.0,25.0,7.0,...,28.0,24.0,17.0,13.0,4.0,40.0,10.0,2.0,19.0,10.0
8758,2022-12-31 22:00:00,32.0,29.0,13.0,19.0,17.0,14.0,11.0,15.0,14.0,...,13.0,18.0,16.0,6.0,2.0,37.0,9.0,7.0,8.0,4.0
8759,2022-12-31 23:00:00,22.0,17.0,10.0,12.0,10.0,15.0,8.0,14.0,14.0,...,18.0,18.0,18.0,6.0,2.0,29.0,14.0,4.0,18.0,3.0

In [95]:
list(df6.columns)

['ZÃ¤hlstelle        Inbetriebnahme',
 '02-MI-JAN-N 01.04.2015',
 '02-MI-JAN-S 01.04.2015',
 '03-MI-SAN-O 01.06.2015',
 '03-MI-SAN-W 01.06.2015',
 '06-FK-FRA-O 01.06.2016',
 '06-FK-FRA-W 01.06.2016',
 '10-PA-BER-N 01.05.2016',
 '10-PA-BER-S 01.05.2016',
 '12-PA-SCH 01.03.2012',
 '13-CW-PRI 01.04.2015',
 '15-SP-KLO-N 01.06.2016',
 '15-SP-KLO-S 01.06.2016',
 '17-SZ-BRE-O 01.05.2016',
 '17-SZ-BRE-W 01.05.2016',
 '18-TS-YOR-O 01.04.2015',
 '18-TS-YOR-W 01.04.2015',
 '19-TS-MON 01.05.2015',
 '20-TS-MAR-N  01.05.2016',
 '20-TS-MAR-S 01.05.2016',
 '21-NK-MAY 01.05.2016',
 '23-TK-KAI 01.05.2016',
 '24-MH-ALB 01.07.2015',
 '26-LI-PUP 01.06.2015',
 '27-RE-MAR 01.05.2015']

In [96]:
list(df_5years.columns)

['ZÃ¤hlstelle        Inbetriebnahme',
 'JannowitzbrÃ¼cke Nord',
 'JannowitzbrÃ¼cke SÃ¼d',
 'InvalidenstraÃe Ost',
 'InvalidenstraÃe West',
 'Frankfurter Allee Ost',
 'Frankfurter Allee West',
 'Berliner StraÃe Nord',
 'Berliner StraÃe SÃ¼d',
 'Schwedter Steg',
 'PrinzregentenstraÃe',
 'KlosterstraÃe Nord',
 'KlosterstraÃe SÃ¼d',
 'Breitenbachplatz Ost',
 'Breitenbachplatz West',
 'YorckstraÃe Ost',
 'YorkstraÃe West',
 'MonumentenstraÃe',
 'Mariendorfer Damm Nord',
 'Mariendorfer Damm SÃ¼d',
 'Maybachufer',
 'Kaisersteg',
 'AlberichstraÃe',
 'Paul-und-Paula-Uferweg',
 'MarkstraÃe',
 'date',
 'Time']

In [104]:
df6= df6.rename(columns={'02-MI-JAN-N 01.04.2015': 'JannowitzbrÃ¼cke Nord', '02-MI-JAN-S 01.04.2015': 'JannowitzbrÃ¼cke SÃ¼d',
                         '03-MI-SAN-O 01.06.2015': 'InvalidenstraÃe Ost', '03-MI-SAN-W 01.06.2015': 'InvalidenstraÃe West',
                         '06-FK-FRA-O 01.06.2016': 'Frankfurter Allee Ost', '06-FK-FRA-W 01.06.2016': 'Frankfurter Allee West',
                         '10-PA-BER-N 01.05.2016': 'Berliner StraÃe Nord', '10-PA-BER-S 01.05.2016': 'Berliner StraÃe SÃ¼d',
                         '12-PA-SCH 01.03.2012': 'Schwedter Steg', '13-CW-PRI 01.04.2015': 'PrinzregentenstraÃe',
                         '15-SP-KLO-N 01.06.2016': 'KlosterstraÃe Nord', '15-SP-KLO-S 01.06.2016': 'KlosterstraÃe SÃ¼d',
                         '17-SZ-BRE-O 01.05.2016': 'Breitenbachplatz Ost', '17-SZ-BRE-W 01.05.2016': 'Breitenbachplatz West',
                         '18-TS-YOR-O 01.04.2015': 'YorckstraÃe Ost', '18-TS-YOR-W 01.04.2015': 'YorkstraÃe West',
                         '19-TS-MON 01.05.2015': 'MonumentenstraÃe', '20-TS-MAR-N  01.05.2016': 'Mariendorfer Damm Nord',
                         '20-TS-MAR-S 01.05.2016': 'Mariendorfer Damm SÃ¼d', '21-NK-MAY 01.05.2016': 'Maybachufer',
                         '23-TK-KAI 01.05.2016': 'Kaisersteg', '24-MH-ALB 01.07.2015': 'AlberichstraÃe',
                         '26-LI-PUP 01.06.2015': 'Paul-und-Paula-Uferweg', '27-RE-MAR 01.05.2015': 'MarkstraÃe'})
df6

,ZÃ¤hlstelle Inbetriebnahme,JannowitzbrÃ¼cke Nord,JannowitzbrÃ¼cke SÃ¼d,InvalidenstraÃe Ost,InvalidenstraÃe West,Frankfurter Allee Ost,Frankfurter Allee West,Berliner StraÃe Nord,Berliner StraÃe SÃ¼d,Schwedter Steg,...,MonumentenstraÃe,Mariendorfer Damm Nord,Mariendorfer Damm SÃ¼d,Maybachufer,Kaisersteg,AlberichstraÃe,Paul-und-Paula-Uferweg,MarkstraÃe,date,Time
0,2022-01-01 00:00:00,10.0,11.0,9.0,8.0,6.0,13.0,7.0,6.0,12.0,...,12.0,0.0,4.0,24.0,2.0,2.0,6.0,3.0,2022-01-01,00:00:00
1,2022-01-01 01:00:00,22.0,13.0,12.0,6.0,4.0,9.0,14.0,12.0,12.0,...,20.0,0.0,1.0,48.0,7.0,4.0,7.0,7.0,2022-01-01,01:00:00
2,2022-01-01 02:00:00,25.0,10.0,14.0,9.0,4.0,12.0,19.0,13.0,12.0,...,32.0,0.0,4.0,22.0,9.0,0.0,13.0,8.0,2022-01-01,02:00:00
3,2022-01-01 03:00:00,12.0,21.0,13.0,17.0,3.0,13.0,9.0,10.0,9.0,...,25.0,0.0,0.0,44.0,7.0,3.0,7.0,5.0,2022-01-01,03:00:00
4,2022-01-01 04:00:00,8.0,6.0,6.0,4.0,0.0,12.0,10.0,13.0,3.0,...,14.0,0.0,3.0,39.0,5.0,0.0,11.0,7.0,2022-01-01,04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00:00,36.0,54.0,28.0,36.0,28.0,25.0,23.0,39.0,30.0,...,44.0,6.0,3.0,89.0,14.0,15.0,38.0,20.0,2022-12-31,19:00:00
8756,2022-12-31 20:00:00,32.0,32.0,20.0,38.0,31.0,23.0,22.0,38.0,29.0,...,44.0,3.0,6.0,65.0,14.0,3.0,20.0,10.0,2022-12-31,20:00:00
8757,2022-12-31 21:00:00,24.0,35.0,16.0,11.0,9.0,18.0,13.0,25.0,7.0,...,17.0,13.0,4.0,40.0,10.0,2.0,19.0,10.0,2022-12-31,21:00:00
8758,2022-12-31 22:00:00,32.0,29.0,13.0,19.0,17.0,14.0,11.0,15.0,14.0,...,16.0,6.0,2.0,37.0,9.0,7.0,8.0,4.0,2022-12-31,22:00:00
8759,2022-12-31 23:00:00,22.0,17.0,10.0,12.0,10.0,15.0,8.0,14.0,14.0,...,18.0,6.0,2.0,29.0,14.0,4.0,18.0,3.0,2022-12-31,23:00:00

In [105]:
list(df6.columns)

['ZÃ¤hlstelle        Inbetriebnahme',
 'JannowitzbrÃ¼cke Nord',
 'JannowitzbrÃ¼cke SÃ¼d',
 'InvalidenstraÃe Ost',
 'InvalidenstraÃe West',
 'Frankfurter Allee Ost',
 'Frankfurter Allee West',
 'Berliner StraÃe Nord',
 'Berliner StraÃe SÃ¼d',
 'Schwedter Steg',
 'PrinzregentenstraÃe',
 'KlosterstraÃe Nord',
 'KlosterstraÃe SÃ¼d',
 'Breitenbachplatz Ost',
 'Breitenbachplatz West',
 'YorckstraÃe Ost',
 'YorkstraÃe West',
 'MonumentenstraÃe',
 'Mariendorfer Damm Nord',
 'Mariendorfer Damm SÃ¼d',
 'Maybachufer',
 'Kaisersteg',
 'AlberichstraÃe',
 'Paul-und-Paula-Uferweg',
 'MarkstraÃe',
 'date',
 'Time']

In [106]:
df6['date'] = df6['ZÃ¤hlstelle        Inbetriebnahme'].dt.date
df6['Time'] = df6['ZÃ¤hlstelle        Inbetriebnahme'].dt.time


df6

,ZÃ¤hlstelle Inbetriebnahme,JannowitzbrÃ¼cke Nord,JannowitzbrÃ¼cke SÃ¼d,InvalidenstraÃe Ost,InvalidenstraÃe West,Frankfurter Allee Ost,Frankfurter Allee West,Berliner StraÃe Nord,Berliner StraÃe SÃ¼d,Schwedter Steg,...,MonumentenstraÃe,Mariendorfer Damm Nord,Mariendorfer Damm SÃ¼d,Maybachufer,Kaisersteg,AlberichstraÃe,Paul-und-Paula-Uferweg,MarkstraÃe,date,Time
0,2022-01-01 00:00:00,10.0,11.0,9.0,8.0,6.0,13.0,7.0,6.0,12.0,...,12.0,0.0,4.0,24.0,2.0,2.0,6.0,3.0,2022-01-01,00:00:00
1,2022-01-01 01:00:00,22.0,13.0,12.0,6.0,4.0,9.0,14.0,12.0,12.0,...,20.0,0.0,1.0,48.0,7.0,4.0,7.0,7.0,2022-01-01,01:00:00
2,2022-01-01 02:00:00,25.0,10.0,14.0,9.0,4.0,12.0,19.0,13.0,12.0,...,32.0,0.0,4.0,22.0,9.0,0.0,13.0,8.0,2022-01-01,02:00:00
3,2022-01-01 03:00:00,12.0,21.0,13.0,17.0,3.0,13.0,9.0,10.0,9.0,...,25.0,0.0,0.0,44.0,7.0,3.0,7.0,5.0,2022-01-01,03:00:00
4,2022-01-01 04:00:00,8.0,6.0,6.0,4.0,0.0,12.0,10.0,13.0,3.0,...,14.0,0.0,3.0,39.0,5.0,0.0,11.0,7.0,2022-01-01,04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00:00,36.0,54.0,28.0,36.0,28.0,25.0,23.0,39.0,30.0,...,44.0,6.0,3.0,89.0,14.0,15.0,38.0,20.0,2022-12-31,19:00:00
8756,2022-12-31 20:00:00,32.0,32.0,20.0,38.0,31.0,23.0,22.0,38.0,29.0,...,44.0,3.0,6.0,65.0,14.0,3.0,20.0,10.0,2022-12-31,20:00:00
8757,2022-12-31 21:00:00,24.0,35.0,16.0,11.0,9.0,18.0,13.0,25.0,7.0,...,17.0,13.0,4.0,40.0,10.0,2.0,19.0,10.0,2022-12-31,21:00:00
8758,2022-12-31 22:00:00,32.0,29.0,13.0,19.0,17.0,14.0,11.0,15.0,14.0,...,16.0,6.0,2.0,37.0,9.0,7.0,8.0,4.0,2022-12-31,22:00:00
8759,2022-12-31 23:00:00,22.0,17.0,10.0,12.0,10.0,15.0,8.0,14.0,14.0,...,18.0,6.0,2.0,29.0,14.0,4.0,18.0,3.0,2022-12-31,23:00:00

In [107]:
df_5years

,ZÃ¤hlstelle Inbetriebnahme,JannowitzbrÃ¼cke Nord,JannowitzbrÃ¼cke SÃ¼d,InvalidenstraÃe Ost,InvalidenstraÃe West,Frankfurter Allee Ost,Frankfurter Allee West,Berliner StraÃe Nord,Berliner StraÃe SÃ¼d,Schwedter Steg,...,MonumentenstraÃe,Mariendorfer Damm Nord,Mariendorfer Damm SÃ¼d,Maybachufer,Kaisersteg,AlberichstraÃe,Paul-und-Paula-Uferweg,MarkstraÃe,date,Time
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,8.0,5.0,5.0,7.0,17.0,...,21.0,0.0,2.0,29.0,6.0,4.0,15.0,6.0,2021-01-01,00:00:00
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,24.0,7.0,23.0,21.0,14.0,...,33.0,2.0,0.0,51.0,7.0,13.0,21.0,4.0,2021-01-01,01:00:00
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,26.0,23.0,24.0,32.0,14.0,...,48.0,1.0,1.0,51.0,6.0,5.0,25.0,11.0,2021-01-01,02:00:00
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,24.0,18.0,20.0,20.0,22.0,...,33.0,1.0,3.0,41.0,5.0,3.0,18.0,9.0,2021-01-01,03:00:00
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,12.0,14.0,19.0,8.0,2.0,...,30.0,1.0,3.0,30.0,6.0,4.0,15.0,1.0,2021-01-01,04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2017-12-31 19:00:00,29.0,29.0,19.0,14.0,20.0,3.0,109.0,18.0,28.0,...,36.0,11.0,8.0,82.0,3.0,3.0,27.0,4.0,2017-12-31,19:00:00
8756,2017-12-31 20:00:00,31.0,22.0,16.0,15.0,26.0,13.0,102.0,27.0,12.0,...,45.0,4.0,7.0,52.0,3.0,0.0,19.0,5.0,2017-12-31,20:00:00
8757,2017-12-31 21:00:00,21.0,18.0,11.0,5.0,7.0,7.0,91.0,13.0,11.0,...,20.0,5.0,1.0,30.0,2.0,3.0,18.0,2.0,2017-12-31,21:00:00
8758,2017-12-31 22:00:00,11.0,18.0,6.0,10.0,10.0,3.0,106.0,9.0,15.0,...,27.0,2.0,0.0,35.0,5.0,0.0,16.0,2.0,2017-12-31,22:00:00
8759,2017-12-31 23:00:00,7.0,9.0,10.0,20.0,5.0,8.0,77.0,6.0,8.0,...,17.0,2.0,0.0,36.0,0.0,0.0,17.0,4.0,2017-12-31,23:00:00

In [108]:
df6

,ZÃ¤hlstelle Inbetriebnahme,JannowitzbrÃ¼cke Nord,JannowitzbrÃ¼cke SÃ¼d,InvalidenstraÃe Ost,InvalidenstraÃe West,Frankfurter Allee Ost,Frankfurter Allee West,Berliner StraÃe Nord,Berliner StraÃe SÃ¼d,Schwedter Steg,...,MonumentenstraÃe,Mariendorfer Damm Nord,Mariendorfer Damm SÃ¼d,Maybachufer,Kaisersteg,AlberichstraÃe,Paul-und-Paula-Uferweg,MarkstraÃe,date,Time
0,2022-01-01 00:00:00,10.0,11.0,9.0,8.0,6.0,13.0,7.0,6.0,12.0,...,12.0,0.0,4.0,24.0,2.0,2.0,6.0,3.0,2022-01-01,00:00:00
1,2022-01-01 01:00:00,22.0,13.0,12.0,6.0,4.0,9.0,14.0,12.0,12.0,...,20.0,0.0,1.0,48.0,7.0,4.0,7.0,7.0,2022-01-01,01:00:00
2,2022-01-01 02:00:00,25.0,10.0,14.0,9.0,4.0,12.0,19.0,13.0,12.0,...,32.0,0.0,4.0,22.0,9.0,0.0,13.0,8.0,2022-01-01,02:00:00
3,2022-01-01 03:00:00,12.0,21.0,13.0,17.0,3.0,13.0,9.0,10.0,9.0,...,25.0,0.0,0.0,44.0,7.0,3.0,7.0,5.0,2022-01-01,03:00:00
4,2022-01-01 04:00:00,8.0,6.0,6.0,4.0,0.0,12.0,10.0,13.0,3.0,...,14.0,0.0,3.0,39.0,5.0,0.0,11.0,7.0,2022-01-01,04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00:00,36.0,54.0,28.0,36.0,28.0,25.0,23.0,39.0,30.0,...,44.0,6.0,3.0,89.0,14.0,15.0,38.0,20.0,2022-12-31,19:00:00
8756,2022-12-31 20:00:00,32.0,32.0,20.0,38.0,31.0,23.0,22.0,38.0,29.0,...,44.0,3.0,6.0,65.0,14.0,3.0,20.0,10.0,2022-12-31,20:00:00
8757,2022-12-31 21:00:00,24.0,35.0,16.0,11.0,9.0,18.0,13.0,25.0,7.0,...,17.0,13.0,4.0,40.0,10.0,2.0,19.0,10.0,2022-12-31,21:00:00
8758,2022-12-31 22:00:00,32.0,29.0,13.0,19.0,17.0,14.0,11.0,15.0,14.0,...,16.0,6.0,2.0,37.0,9.0,7.0,8.0,4.0,2022-12-31,22:00:00
8759,2022-12-31 23:00:00,22.0,17.0,10.0,12.0,10.0,15.0,8.0,14.0,14.0,...,18.0,6.0,2.0,29.0,14.0,4.0,18.0,3.0,2022-12-31,23:00:00

In [109]:
df10=df_5years.append(df6)
df10

,ZÃ¤hlstelle Inbetriebnahme,JannowitzbrÃ¼cke Nord,JannowitzbrÃ¼cke SÃ¼d,InvalidenstraÃe Ost,InvalidenstraÃe West,Frankfurter Allee Ost,Frankfurter Allee West,Berliner StraÃe Nord,Berliner StraÃe SÃ¼d,Schwedter Steg,...,MonumentenstraÃe,Mariendorfer Damm Nord,Mariendorfer Damm SÃ¼d,Maybachufer,Kaisersteg,AlberichstraÃe,Paul-und-Paula-Uferweg,MarkstraÃe,date,Time
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,8.0,5.0,5.0,7.0,17.0,...,21.0,0.0,2.0,29.0,6.0,4.0,15.0,6.0,2021-01-01,00:00:00
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,24.0,7.0,23.0,21.0,14.0,...,33.0,2.0,0.0,51.0,7.0,13.0,21.0,4.0,2021-01-01,01:00:00
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,26.0,23.0,24.0,32.0,14.0,...,48.0,1.0,1.0,51.0,6.0,5.0,25.0,11.0,2021-01-01,02:00:00
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,24.0,18.0,20.0,20.0,22.0,...,33.0,1.0,3.0,41.0,5.0,3.0,18.0,9.0,2021-01-01,03:00:00
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,12.0,14.0,19.0,8.0,2.0,...,30.0,1.0,3.0,30.0,6.0,4.0,15.0,1.0,2021-01-01,04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00:00,36.0,54.0,28.0,36.0,28.0,25.0,23.0,39.0,30.0,...,44.0,6.0,3.0,89.0,14.0,15.0,38.0,20.0,2022-12-31,19:00:00
8756,2022-12-31 20:00:00,32.0,32.0,20.0,38.0,31.0,23.0,22.0,38.0,29.0,...,44.0,3.0,6.0,65.0,14.0,3.0,20.0,10.0,2022-12-31,20:00:00
8757,2022-12-31 21:00:00,24.0,35.0,16.0,11.0,9.0,18.0,13.0,25.0,7.0,...,17.0,13.0,4.0,40.0,10.0,2.0,19.0,10.0,2022-12-31,21:00:00
8758,2022-12-31 22:00:00,32.0,29.0,13.0,19.0,17.0,14.0,11.0,15.0,14.0,...,16.0,6.0,2.0,37.0,9.0,7.0,8.0,4.0,2022-12-31,22:00:00
8759,2022-12-31 23:00:00,22.0,17.0,10.0,12.0,10.0,15.0,8.0,14.0,14.0,...,18.0,6.0,2.0,29.0,14.0,4.0,18.0,3.0,2022-12-31,23:00:00

In [110]:
df10.to_excel("6_years.xlsx")