In [42]:
import openpyxl
workbook=openpyxl.load_workbook('gesamtdatei_stundenwerte1.xlsx')
workbook.get_sheet_names()

<ipython-input-42-1075f6671aef>:3: DeprecationWarning: Call to deprecated function get_sheet_names (Use wb.sheetnames).
  workbook.get_sheet_names()

['Hinweise',
 'Legende',
 'Standortdaten',
 'Jahresdatei 2012',
 'Jahresdatei 2013',
 'Jahresdatei 2014',
 'Jahresdatei 2015',
 'Jahresdatei 2016',
 'Jahresdatei 2017',
 'Jahresdatei 2018',
 'Jahresdatei 2019',
 'Jahresdatei 2020',
 'Jahresdatei 2021']

In [15]:
print(workbook.sheetnames)

['Hinweise', 'Legende', 'Standortdaten', 'Jahresdatei 2012', 'Jahresdatei 2013', 'Jahresdatei 2014', 'Jahresdatei 2015', 'Jahresdatei 2016', 'Jahresdatei 2017', 'Jahresdatei 2018', 'Jahresdatei 2019', 'Jahresdatei 2020', 'Jahresdatei 2021']

In [18]:
Standortdaten=workbook.get_sheet_by_name('Standortdaten')

<ipython-input-18-ccda1a4182f4>:1: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
  Standortdaten=workbook.get_sheet_by_name('Standortdaten')

In [20]:
workbook.remove_sheet(Standortdaten)

<ipython-input-20-010f6b194d74>:1: DeprecationWarning: Call to deprecated function remove_sheet (Use wb.remove(worksheet) or del wb[sheetname]).
  workbook.remove_sheet(Standortdaten)

In [21]:
Hinweise=workbook.get_sheet_by_name('Hinweise')
Legende=workbook.get_sheet_by_name('Legende')

<ipython-input-21-f7581d76972b>:1: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
  Hinweise=workbook.get_sheet_by_name('Hinweise')
<ipython-input-21-f7581d76972b>:2: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
  Legende=workbook.get_sheet_by_name('Legende')

In [22]:
workbook.remove_sheet(Hinweise)

<ipython-input-22-97410fd07ff2>:1: DeprecationWarning: Call to deprecated function remove_sheet (Use wb.remove(worksheet) or del wb[sheetname]).
  workbook.remove_sheet(Hinweise)

In [23]:
workbook.remove_sheet(Legende)

<ipython-input-23-713b7318e16e>:1: DeprecationWarning: Call to deprecated function remove_sheet (Use wb.remove(worksheet) or del wb[sheetname]).
  workbook.remove_sheet(Legende)

In [24]:
print(workbook.sheetnames)

['Jahresdatei 2012', 'Jahresdatei 2013', 'Jahresdatei 2014', 'Jahresdatei 2015', 'Jahresdatei 2016', 'Jahresdatei 2017', 'Jahresdatei 2018', 'Jahresdatei 2019', 'Jahresdatei 2020', 'Jahresdatei 2021']

In [27]:
workbook.sheetnames

['Jahresdatei 2012',
 'Jahresdatei 2013',
 'Jahresdatei 2014',
 'Jahresdatei 2015',
 'Jahresdatei 2016',
 'Jahresdatei 2017',
 'Jahresdatei 2018',
 'Jahresdatei 2019',
 'Jahresdatei 2020',
 'Jahresdatei 2021']

In [70]:

from datetime import datetime

import numpy as np
import pandas as pd

In [71]:
xls = pd.ExcelFile('gesamtdatei_stundenwerte1.xlsx')
df1 = pd.read_excel(xls, 'Jahresdatei 2021')
df1

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015,06-CW-JU-O 27.07.2021,06-CW-JU-W 27.07.2021,02-MI-AL-W 16.12.2021
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,NaN,NaN,8.0,5.0,5.0,...,0.0,2.0,29.0,6.0,4.0,15.0,6.0,NaN,NaN,NaN
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,NaN,NaN,24.0,7.0,23.0,...,2.0,0.0,51.0,7.0,13.0,21.0,4.0,NaN,NaN,NaN
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,NaN,NaN,26.0,23.0,24.0,...,1.0,1.0,51.0,6.0,5.0,25.0,11.0,NaN,NaN,NaN
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,NaN,NaN,24.0,18.0,20.0,...,1.0,3.0,41.0,5.0,3.0,18.0,9.0,NaN,NaN,NaN
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,NaN,NaN,12.0,14.0,19.0,...,1.0,3.0,30.0,6.0,4.0,15.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2021-12-31 19:00:00,32.0,27.0,21.0,29.0,NaN,NaN,3.0,29.0,19.0,...,0.0,4.0,74.0,4.0,10.0,17.0,14.0,13.0,18.0,22.0
8756,2021-12-31 20:00:00,17.0,21.0,14.0,14.0,NaN,NaN,2.0,10.0,13.0,...,0.0,3.0,56.0,15.0,1.0,13.0,13.0,7.0,8.0,8.0
8757,2021-12-31 21:00:00,13.0,23.0,15.0,15.0,NaN,NaN,2.0,8.0,14.0,...,0.0,1.0,26.0,7.0,4.0,4.0,6.0,2.0,8.0,20.0
8758,2021-12-31 22:00:00,25.0,15.0,8.0,11.0,NaN,NaN,2.0,13.0,7.0,...,0.0,1.0,19.0,6.0,2.0,5.0,9.0,5.0,9.0,9.0
8759,2021-12-31 23:00:00,10.0,17.0,10.0,11.0,NaN,NaN,3.0,13.0,6.0,...,0.0,1.0,22.0,3.0,0.0,12.0,4.0,13.0,5.0,9.0

In [78]:
#df1.info()
#df1['Date']= pd.to_datetime(df1['ZÃ¤hlstelle Inbetriebnahme'])

df1['ZÃ¤hlstelle        Inbetriebnahme']

0      2021-01-01 00:00:00
1      2021-01-01 01:00:00
2      2021-01-01 02:00:00
3      2021-01-01 03:00:00
4      2021-01-01 04:00:00
               ...
8755   2021-12-31 19:00:00
8756   2021-12-31 20:00:00
8757   2021-12-31 21:00:00
8758   2021-12-31 22:00:00
8759   2021-12-31 23:00:00
Name: ZÃ¤hlstelle        Inbetriebnahme, Length: 8760, dtype: datetime64[ns]

In [83]:
df1['date'] = df1['ZÃ¤hlstelle        Inbetriebnahme'].dt.date
df1['Time'] = df1['ZÃ¤hlstelle        Inbetriebnahme'].dt.time
df1

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015,06-CW-JU-O 27.07.2021,06-CW-JU-W 27.07.2021,02-MI-AL-W 16.12.2021,Dates,Time,date
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,NaN,NaN,8.0,5.0,5.0,...,6.0,4.0,15.0,6.0,NaN,NaN,NaN,2021-01-01,00:00:00,2021-01-01
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,NaN,NaN,24.0,7.0,23.0,...,7.0,13.0,21.0,4.0,NaN,NaN,NaN,2021-01-01,01:00:00,2021-01-01
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,NaN,NaN,26.0,23.0,24.0,...,6.0,5.0,25.0,11.0,NaN,NaN,NaN,2021-01-01,02:00:00,2021-01-01
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,NaN,NaN,24.0,18.0,20.0,...,5.0,3.0,18.0,9.0,NaN,NaN,NaN,2021-01-01,03:00:00,2021-01-01
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,NaN,NaN,12.0,14.0,19.0,...,6.0,4.0,15.0,1.0,NaN,NaN,NaN,2021-01-01,04:00:00,2021-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2021-12-31 19:00:00,32.0,27.0,21.0,29.0,NaN,NaN,3.0,29.0,19.0,...,4.0,10.0,17.0,14.0,13.0,18.0,22.0,2021-12-31,19:00:00,2021-12-31
8756,2021-12-31 20:00:00,17.0,21.0,14.0,14.0,NaN,NaN,2.0,10.0,13.0,...,15.0,1.0,13.0,13.0,7.0,8.0,8.0,2021-12-31,20:00:00,2021-12-31
8757,2021-12-31 21:00:00,13.0,23.0,15.0,15.0,NaN,NaN,2.0,8.0,14.0,...,7.0,4.0,4.0,6.0,2.0,8.0,20.0,2021-12-31,21:00:00,2021-12-31
8758,2021-12-31 22:00:00,25.0,15.0,8.0,11.0,NaN,NaN,2.0,13.0,7.0,...,6.0,2.0,5.0,9.0,5.0,9.0,9.0,2021-12-31,22:00:00,2021-12-31
8759,2021-12-31 23:00:00,10.0,17.0,10.0,11.0,NaN,NaN,3.0,13.0,6.0,...,3.0,0.0,12.0,4.0,13.0,5.0,9.0,2021-12-31,23:00:00,2021-12-31

In [84]:
xls2 = pd.ExcelFile('export_2021.xlsx')
df2 = pd.read_excel(xls2, 'Export')
df2

           date  tavg  tmin  tmax  prcp  snow   wdir  wspd  wpgt    pres  tsun
0    2021-01-01   1.0   0.1   1.8   1.2   NaN  195.0   8.2  20.4  1007.7   NaN
1    2021-01-02   0.8  -1.1   2.9   0.0   NaN  176.0   8.1  22.2  1014.5   NaN
2    2021-01-03   0.3  -0.2   0.7   7.2   NaN   57.0  18.2  37.0  1015.8   NaN
3    2021-01-04   0.8   0.5   1.0   3.4   NaN   51.0  14.9  31.5  1017.2   NaN
4    2021-01-05   1.3   0.6   2.1   2.3   NaN   30.0  15.1  31.5  1016.9   NaN
..          ...   ...   ...   ...   ...   ...    ...   ...   ...     ...   ...
360  2021-12-27  -4.6  -8.2  -2.1   0.0   NaN  114.0  17.8  35.2  1008.9   NaN
361  2021-12-28  -0.2  -3.2   2.0   2.4   NaN  131.0  17.0  33.3  1000.5   NaN
362  2021-12-29   3.0   1.9   3.9   1.4   NaN  232.0   8.5  20.4  1004.1   NaN
363  2021-12-30   7.6   3.9  11.4   3.3   NaN  233.0  14.1  38.9  1011.1   NaN
364  2021-12-31  11.8  11.3  12.4   5.2   NaN  257.0  20.8  42.6  1014.4   NaN

[365 rows x 11 columns]

In [61]:
#df = pd.concat([df1, df2, numerical_df], axis=1)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    365 non-null    object
 1   tavg    364 non-null    float64
 2   tmin    364 non-null    float64
 3   tmax    364 non-null    float64
 4   prcp    364 non-null    float64
 5   snow    0 non-null      float64
 6   wdir    364 non-null    float64
 7   wspd    364 non-null    float64
 8   wpgt    364 non-null    float64
 9   pres    364 non-null    float64
 10  tsun    0 non-null      float64
dtypes: float64(10), object(1)
memory usage: 31.5+ KB

In [88]:
df1

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015,06-CW-JU-O 27.07.2021,06-CW-JU-W 27.07.2021,02-MI-AL-W 16.12.2021,Dates,Time,date
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,NaN,NaN,8.0,5.0,5.0,...,6.0,4.0,15.0,6.0,NaN,NaN,NaN,2021-01-01,00:00:00,2021-01-01
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,NaN,NaN,24.0,7.0,23.0,...,7.0,13.0,21.0,4.0,NaN,NaN,NaN,2021-01-01,01:00:00,2021-01-01
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,NaN,NaN,26.0,23.0,24.0,...,6.0,5.0,25.0,11.0,NaN,NaN,NaN,2021-01-01,02:00:00,2021-01-01
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,NaN,NaN,24.0,18.0,20.0,...,5.0,3.0,18.0,9.0,NaN,NaN,NaN,2021-01-01,03:00:00,2021-01-01
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,NaN,NaN,12.0,14.0,19.0,...,6.0,4.0,15.0,1.0,NaN,NaN,NaN,2021-01-01,04:00:00,2021-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2021-12-31 19:00:00,32.0,27.0,21.0,29.0,NaN,NaN,3.0,29.0,19.0,...,4.0,10.0,17.0,14.0,13.0,18.0,22.0,2021-12-31,19:00:00,2021-12-31
8756,2021-12-31 20:00:00,17.0,21.0,14.0,14.0,NaN,NaN,2.0,10.0,13.0,...,15.0,1.0,13.0,13.0,7.0,8.0,8.0,2021-12-31,20:00:00,2021-12-31
8757,2021-12-31 21:00:00,13.0,23.0,15.0,15.0,NaN,NaN,2.0,8.0,14.0,...,7.0,4.0,4.0,6.0,2.0,8.0,20.0,2021-12-31,21:00:00,2021-12-31
8758,2021-12-31 22:00:00,25.0,15.0,8.0,11.0,NaN,NaN,2.0,13.0,7.0,...,6.0,2.0,5.0,9.0,5.0,9.0,9.0,2021-12-31,22:00:00,2021-12-31
8759,2021-12-31 23:00:00,10.0,17.0,10.0,11.0,NaN,NaN,3.0,13.0,6.0,...,3.0,0.0,12.0,4.0,13.0,5.0,9.0,2021-12-31,23:00:00,2021-12-31

In [90]:
df= pd.merge(df1, df2, how='left', on='date')
df

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,NaN,NaN,8.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,NaN,NaN,24.0,7.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,NaN,NaN,26.0,23.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,NaN,NaN,24.0,18.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,NaN,NaN,12.0,14.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2021-12-31 19:00:00,32.0,27.0,21.0,29.0,NaN,NaN,3.0,29.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8756,2021-12-31 20:00:00,17.0,21.0,14.0,14.0,NaN,NaN,2.0,10.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8757,2021-12-31 21:00:00,13.0,23.0,15.0,15.0,NaN,NaN,2.0,8.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8758,2021-12-31 22:00:00,25.0,15.0,8.0,11.0,NaN,NaN,2.0,13.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8759,2021-12-31 23:00:00,10.0,17.0,10.0,11.0,NaN,NaN,3.0,13.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN